<a href="https://colab.research.google.com/github/harshroy7632/Basic-analysis-on-weather-data/blob/main/weather_report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = pd.read_csv("/content/1. Weather Data.csv")

In [ ]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

Data Exploration

In [ ]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [ ]:
data.shape

(8784, 8)

In [ ]:
data.index

RangeIndex(start=0, stop=8784, step=1)

In [ ]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='object')

In [ ]:
data.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [ ]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64

All Unique Values of wind speed

In [ ]:
data['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

Checking When weather was exactly clear

In [ ]:
data.Weather.value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: Weather, dtype: int64

In [ ]:
data[data.Weather == 'Clear']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
114,1/5/2012 18:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,1/5/2012 19:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,1/5/2012 20:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,1/5/2012 21:00,-9.0,-14.8,63,13,25.0,100.83,Clear
...,...,...,...,...,...,...,...,...
8646,12/26/2012 6:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,12/28/2012 10:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,12/29/2012 1:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,12/29/2012 2:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

In [ ]:
data[data['Wind Speed_km/h']==4]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
96,1/5/2012 0:00,-8.8,-11.7,79,4,9.7,100.32,Snow
101,1/5/2012 5:00,-7.0,-9.5,82,4,4.0,100.19,Snow
146,1/7/2012 2:00,-8.1,-11.1,79,4,19.3,100.15,Cloudy
...,...,...,...,...,...,...,...,...
8768,12/31/2012 8:00,-8.6,-10.3,87,4,3.2,101.14,Snow Showers
8769,12/31/2012 9:00,-8.1,-9.6,89,4,2.4,101.09,Snow
8770,12/31/2012 10:00,-7.4,-8.9,89,4,6.4,101.05,"Snow,Fog"
8772,12/31/2012 12:00,-5.8,-7.5,88,4,12.9,100.78,Snow
8773,12/31/2012 13:00,-4.6,-6.6,86,4,12.9,100.63,Snow

Finding all the null values

In [ ]:
data.isnull()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
8779,False,False,False,False,False,False,False,False
8780,False,False,False,False,False,False,False,False
8781,False,False,False,False,False,False,False,False
8782,False,False,False,False,False,False,False,False
8783,False,False,False,False,False,False,False,False

In [ ]:
data.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

If there is null value in the dataset we can do two things:
1.) remove all the null values  from the dataset by using ('data.dropna()')
2.) replace all null values by zero(0) by using ('data.fillna(0)')

Apllying some simple mathematical formulas on the some columns

In [ ]:
data.Visibility_km.mean()

27.664446721311478

In [ ]:
data.Press_kPa.median()

101.07

In [ ]:
data['Wind Speed_km/h'].mode()

0    9
dtype: int64

In [ ]:
data['Rel Hum_%'].std()

16.91888147007662

In [ ]:
data[(data['Wind Speed_km/h'] > 24) & (data.Visibility_km==25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
23,1/1/2012 23:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,1/2/2012 0:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,1/2/2012 1:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,1/2/2012 2:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,1/2/2012 3:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8705,12/28/2012 17:00,-8.6,-12.0,76,26,25.0,101.34,Mainly Clear
8753,12/30/2012 17:00,-12.1,-15.8,74,28,25.0,101.26,Mainly Clear
8755,12/30/2012 19:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8759,12/30/2012 23:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,12/31/2012 0:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

Mean value of each column against each Weather condition

In [ ]:
data.groupby('Weather').mean()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather,,,,,,
Clear,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000
"Drizzle,Snow",1.050000,0.150000,93.500000,14.000000,10.500000,100.890000
"Drizzle,Snow,Fog",0.693333,0.120000,95.866667,15.533333,5.513333,99.281333
Fog,4.303333,3.159333,92.286667,7.946667,6.248000,101.184067
Freezing Drizzle,-5.657143,-8.000000,83.571429,16.571429,9.200000,100.202857
"Freezing Drizzle,Fog",-2.533333,-4.183333,88.500000,17.000000,5.266667,100.441667
"Freezing Drizzle,Haze",-5.433333,-8.000000,82.000000,10.333333,2.666667,100.316667
"Freezing Drizzle,Snow",-5.109091,-7.072727,86.090909,16.272727,5.872727,100.520909
Freezing Fog,-7.575000,-9.250000,87.750000,4.750000,0.650000,102.320000
Freezing Rain,-3.885714,-6.078571,84.642857,19.214286,8.242857,99.647143
"Freezing Rain,Fog",-2.225000,-3.750000,89.500000,15.500000,7.550000,99.945000
"Freezing Rain,Haze",-4.900000,-7.450000,82.500000,7.500000,2.400000,100.375000
"Freezing Rain,Ice Pellets,Fog",-2.600000,-3.700000,92.000000,28.000000,8.000000,100.950000
"Freezing Rain,Snow Grains",-5.000000,-7.300000,84.000000,32.000000,4.800000,98.560000
Haze,-0.200000,-2.975000,81.625000,10.437500,7.831250,101.482500
Mainly Clear,12.558927,4.581671,60.667142,14.144824,34.264862,101.248832
"Moderate Rain,Fog",1.700000,0.800000,94.000000,17.000000,6.400000,99.980000
Moderate Snow,-5.525000,-7.250000,87.750000,33.750000,0.750000,100.275000
"Moderate Snow,Blowing Snow",-5.450000,-6.500000,92.500000,40.000000,0.600000,100.570000
Mostly Cloudy,10.574287,3.131174,62.102465,15.813920,31.253842,101.025288
Rain,9.786275,7.042810,83.624183,19.254902,18.856536,100.233333
Rain Showers,13.722340,9.187766,75.159574,17.132979,22.816489,100.404043
"Rain Showers,Fog",12.800000,12.100000,96.000000,13.000000,6.400000,99.830000
"Rain Showers,Snow Showers",2.150000,-1.500000,76.500000,22.500000,21.700000,101.100000
"Rain,Fog",8.273276,7.219828,93.189655,14.793103,6.873276,100.500862
"Rain,Haze",4.633333,2.066667,83.333333,11.666667,6.700000,100.540000
"Rain,Ice Pellets",0.600000,-0.600000,92.000000,24.000000,9.700000,100.120000
"Rain,Snow",1.055556,-0.566667,89.000000,28.388889,11.672222,99.951111
"Rain,Snow Grains",1.900000,-2.100000,75.000000,26.000000,25.000000,100.600000
"Rain,Snow,Fog",0.800000,0.300000,96.000000,9.000000,6.400000,100.730000
"Rain,Snow,Ice Pellets",1.100000,-0.175000,91.500000,23.250000,6.000000,100.105000
Snow,-4.524103,-7.623333,79.307692,20.038462,11.171795,100.536103
Snow Pellets,0.700000,-6.400000,59.000000,35.000000,2.400000,99.700000
Snow Showers,-3.506667,-7.866667,72.350000,19.233333,20.158333,100.963500
"Snow Showers,Fog",-10.675000,-11.900000,90.750000,13.750000,7.025000,101.292500
"Snow,Blowing Snow",-5.410526,-7.621053,84.473684,34.842105,4.105263,99.704737
"Snow,Fog",-5.075676,-6.364865,90.675676,17.324324,4.537838,100.688649
"Snow,Haze",-4.020000,-6.860000,80.600000,5.000000,4.640000,100.782000
"Snow,Ice Pellets",-1.883333,-3.666667,87.666667,23.833333,7.416667,100.548333
Thunderstorms,24.150000,19.750000,77.000000,7.500000,24.550000,100.230000
"Thunderstorms,Heavy Rain Showers",10.900000,9.000000,88.000000,9.000000,2.400000,100.260000
"Thunderstorms,Moderate Rain Showers,Fog",19.600000,18.500000,93.000000,15.000000,3.200000,100.010000
"Thunderstorms,Rain",20.433333,18.533333,89.000000,15.666667,19.833333,100.420000
"Thunderstorms,Rain Showers",20.037500,17.618750,86.375000,18.312500,15.893750,100.233750
"Thunderstorms,Rain Showers,Fog",21.600000,18.700000,84.000000,19.666667,9.700000,100.063333
"Thunderstorms,Rain,Fog",20.600000,18.600000,88.000000,19.000000,4.800000,100.080000

Finding all instances when 'Weather is Clear' or 'Visibility is above 40'.

In [ ]:
data[(data['Weather']=='Clear')| (data.Visibility_km > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
67,1/3/2012 19:00,-16.9,-24.8,50,24,25.0,101.74,Clear
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear

Find all instances when :
A. 'Weather is Clear' and 'Relative Humidity is greater than 50'
or
B. 'Visibility is above 40'

In [ ]:
data[((data.Weather== 'Clear') & (data['Rel Hum_%']>50)) | (data.Visibility_km > 40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
106,1/5/2012 10:00,-6.0,-10.0,73,17,48.3,100.45,Mainly Clear
107,1/5/2012 11:00,-5.6,-10.2,70,22,48.3,100.41,Mainly Clear
108,1/5/2012 12:00,-4.7,-9.6,69,20,48.3,100.38,Mainly Clear
109,1/5/2012 13:00,-4.4,-9.7,66,26,48.3,100.40,Mainly Clear
110,1/5/2012 14:00,-5.1,-10.7,65,22,48.3,100.46,Mainly Clear
...,...,...,...,...,...,...,...,...
8749,12/30/2012 13:00,-12.4,-16.2,73,37,48.3,100.92,Mostly Cloudy
8750,12/30/2012 14:00,-11.8,-16.1,70,37,48.3,100.96,Mainly Clear
8751,12/30/2012 15:00,-11.3,-15.6,70,32,48.3,101.05,Mainly Clear
8752,12/30/2012 16:00,-11.4,-15.5,72,26,48.3,101.15,Mainly Clear
8756,12/30/2012 20:00,-13.8,-16.5,80,24,25.0,101.52,Clear